# deploy.ps1 - Automated Antigravity Native Config Deployer
# Usage: .\deploy.ps1

$ErrorActionPreference = "Stop"

$GEMINI_ROOT = "$env:USERPROFILE\.gemini"
$CONFIG_ROOT = "$GEMINI_ROOT\config"
$SKILLS_TARGET = "$CONFIG_ROOT\skills"
$HOOKS_TARGET = "$CONFIG_ROOT\hooks"
$HOOKS_JSON_TARGET = "$CONFIG_ROOT\hooks.json"
$GEMINI_MD_TARGET = "$GEMINI_ROOT\GEMINI.md"
$MCP_CONFIG_TARGET = "$CONFIG_ROOT\mcp_config.json"

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Deploying Antigravity Native Configuration" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

# 1. Ensure Target Folders Exist
Write-Host "[1/6] Creating config directories..." -ForegroundColor Yellow
$null = New-Item -ItemType Directory -Force -Path $SKILLS_TARGET
$null = New-Item -ItemType Directory -Force -Path $HOOKS_TARGET

# 2. Deploy Skills
Write-Host "[2/6] Deploying skills to $SKILLS_TARGET..." -ForegroundColor Yellow
if (Test-Path "$SKILLS_TARGET\*") {
    Remove-Item -Path "$SKILLS_TARGET\*" -Recurse -Force -ErrorAction SilentlyContinue
}
Copy-Item -Path "skills\*" -Destination $SKILLS_TARGET -Recurse -Force
Write-Host "  Skills synced successfully." -ForegroundColor Green

# 3. Concatenate and Deploy Rules to GEMINI.md
Write-Host "[3/5] Compiling rules into $GEMINI_MD_TARGET..." -ForegroundColor Yellow
$RuleFiles = @(
    "rules\authoring-rules.md",
    "rules\csharp-guidelines.md",
    "rules\debugging.md",
    "rules\testing-anti-patterns.md",
    "rules\condition-based-waiting.md",
    "rules\subagent-orchestration.md",
    "rules\code-review.md"
)

$GeminiContent = @(
    "# Global Antigravity Rules & Guidelines",
    "",
    "This file is compiled automatically from the ai-workspace-nexus rules repository.",
    "Do not edit this file directly; modify the rules in the repository and run deploy.ps1.",
    ""
)

foreach ($RuleFile in $RuleFiles) {
    if (Test-Path $RuleFile) {
        $FileName = Split-Path $RuleFile -Leaf
        $Title = $FileName -replace "\.md$", ""
        
        $GeminiContent += "---"
        $GeminiContent += "# Rule: $Title"
        $GeminiContent += ""
        # Read file with UTF-8 encoding
        $GeminiContent += (Get-Content -Raw -Encoding UTF8 -Path $RuleFile)
        $GeminiContent += ""
        Write-Host "  Merged: $RuleFile" -ForegroundColor DarkGreen
    } else {
        Write-Warning "Rule file not found: $RuleFile"
    }
}

# Write file with UTF-8 encoding
[System.IO.File]::WriteAllText($GEMINI_MD_TARGET, ($GeminiContent -join "`r`n"), [System.Text.Encoding]::UTF8)
Write-Host "  Global rules merged successfully." -ForegroundColor Green

# 4. Deploy Hooks & Rewrite hooks.json
Write-Host "[4/5] Deploying hooks to $HOOKS_TARGET..." -ForegroundColor Yellow
if (Test-Path "$HOOKS_TARGET\*") {
    Remove-Item -Path "$HOOKS_TARGET\*" -Recurse -Force -ErrorAction SilentlyContinue
}
Copy-Item -Path "hooks\*" -Destination $HOOKS_TARGET -Recurse -Force

Write-Host "  Configuring hooks.json..." -ForegroundColor Yellow
if (Test-Path "hooks.json") {
    $HooksJsonRaw = Get-Content -Raw -Encoding UTF8 -Path "hooks.json"
    
    # Generate the absolute path to run-hook.cmd with forward slashes
    $AbsHookCmd = "$HOOKS_TARGET\run-hook.cmd" -replace '\\', '/'
    
    # Replace relative command "./hooks/run-hook.cmd" with absolute path
    $HooksJsonUpdated = $HooksJsonRaw -replace '\./hooks/run-hook.cmd', $AbsHookCmd
    
    [System.IO.File]::WriteAllText($HOOKS_JSON_TARGET, $HooksJsonUpdated, [System.Text.Encoding]::UTF8)
    Write-Host "  Hooks configured successfully with absolute path: $AbsHookCmd" -ForegroundColor Green
} else {
    Write-Warning "hooks.json not found in repository."
}

# 5. Cleanup Obsolete Plugins Directory
Write-Host "[5/6] Cleaning up obsolete custom plugins directory..." -ForegroundColor Yellow
$PluginsPath = "$CONFIG_ROOT\plugins"
if (Test-Path $PluginsPath) {
    Remove-Item -Path $PluginsPath -Recurse -Force
    Write-Host "  Obsolete plugins folder deleted." -ForegroundColor Green
} else {
    Write-Host "  No obsolete plugins folder found. Skipping." -ForegroundColor DarkGreen
}

# 6. Deploy Custom Agents
Write-Host "[6/6] Deploying custom agents to $CONFIG_ROOT\agents..." -ForegroundColor Yellow
$null = New-Item -ItemType Directory -Force -Path "$CONFIG_ROOT\agents"
if (Test-Path "$CONFIG_ROOT\agents\*") {
    Remove-Item -Path "$CONFIG_ROOT\agents\*" -Recurse -Force -ErrorAction SilentlyContinue
}
Copy-Item -Path "agents\*" -Destination "$CONFIG_ROOT\agents" -Recurse -Force
Write-Host "  Agents synced successfully." -ForegroundColor Green

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Deployment completed successfully!" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
